agent: "PPG"
env_name: "Classic Control"
env_id: "MountainCar-v0"
vectorize: "Dummy_Gym"
representation: "Basic_MLP"
policy: "Categorical_PPG"
runner: "DRL"

representation_hidden_size: [128,]
actor_hidden_size: [128,]
critic_hidden_size: [128,]
activation: "leaky_relu"

seed: 1
parallels: 10
running_steps: 300000
horizon_size: 256  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epoch: 1
policy_nepoch: 4
value_nepoch: 8 
aux_nepoch: 8
n_minibatch: 1
learning_rate: 0.001

ent_coef: 0.01
clip_range: 0.2
kl_beta: 1.0
gamma: 0.98
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 1
log_dir: "./logs/ppg/"
model_dir: "./models/ppg/"
