agent: "VDN"  # the learning algorithms_marl
env_name: "atari"  # Name of the environment.
env_id: "basketball_pong_v3"
env_seed: 1  # The random seed of the environment.
obs_type: "grayscale_image"  # choice for Atari env: ram, rgb_image, grayscale_image
img_size: [84, 84]  # default is 210 x 160 in gym[Atari]
num_stack: 4  # frame stack trick
frame_skip: 4  # frame skip trick
noop_max: 30  # Do no-op action for a number of steps in [1, noop_max].
learner: "VDN_Learner"
policy: "Mixing_Q_network"
representation: "Basic_CNN"
vectorize: "DummyVecMultiAgentEnv"
runner: "MARL"  # Runner

# the following three arguments are for "Basic_CNN" representation.
use_cnn: True  # Whether to use convolutional neural networks as representation.
filters: [32, 32, 64, 64]
kernels: [8, 4, 4, 4]
strides: [4, 2, 2, 2]
actor_hidden_size: [128, 128]  # A list of hidden units for each layer of actor network.
critic_hidden_size: [128, 128]  # A list of hidden units for each layer of critic network.

use_rnn: False  # Whether to use recurrent neural networks.
rnn: "GRU"  # Choice of recurrent networks: GRU or LSTM.
N_recurrent_layers: 1  # Number of recurrent layers.
fc_hidden_sizes: [64, ]
recurrent_hidden_size: 64
dropout: 0  # dropout should be a number in range [0, 1], the probability of an element being zeroed.

representation_hidden_size: [64, ]
q_hidden_size: [64, ]  # the units for each hidden layer
activation: "relu"  # The activation function of each hidden layer.

seed: 1069
parallels: 5
buffer_size: 500000
batch_size: 32
learning_rate: 0.0001
gamma: 0.99  # discount factor
double_q: True  # use double q learning

start_greedy: 0.5
end_greedy: 0.05
decay_step_greedy: 1000000
start_training: 10000  # start training after n steps
running_steps: 50000000  # 10M
training_frequency: 1
sync_frequency: 500

use_grad_clip: False
grad_clip_norm: 0.5
use_parameter_sharing: True
use_actions_mask: False

eval_interval: 500000
test_episode: 5
log_dir: "./logs/vdn/"
model_dir: "./models/vdn/"
