agent: "Duel_DQN"
env_name: "Box2D"
env_id: "LunarLander-v2"
vectorize: "Dummy_Gym"
policy: "Duel_Q_network"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128, ]
q_hidden_size: [128, ]
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 100000
batch_size: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 20000
sync_frequency: 50
training_frequency: 1
running_steps: 500000
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 1
log_dir: "./logs/dueldqn/"
model_dir: "./models/dueldqn/"
