dl_toolbox: "torch"  # The deep learning toolbox. Values: "torch", "mindspore", "tensorlayer"

runner: "DRL"  # Values: "DRL", "MARL", "Mean_Field_MARL"

parallels: 4
seed: 2910
vectorize: "Dummy"  # "Dummy" for DRL, "Dummy_MAS" for MARL
train_at_step: False  # True: train once after a step; False: train after an episode.
render: False
render_mode: 'human'  # choices: ['human', 'rgb_array']
render_delay: 0.0  # s
test_mode: False


device: "cuda:0"

# PyTorch: "cpu", "cuda:0";
# TensorFlow: "cpu/CPU", "gpu/GPU";
# MindSpore: "CPU", "GPU", "Ascend", "Davinci"

