agent: "TD3"
env_name: "MuJoCo"
env_id: "Ant-v4"
policy: "TD3_Policy"
representation: "Basic_Identical"

actor_hidden_size: [256, ]
critic_hidden_size: [256, ]
activation: "LeakyReLU"

seed: 6782
parallels: 4  # number of environments
n_size: 50000
batch_size: 256
actor_learning_rate: 0.001
actor_update_decay: 3
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.01

start_noise: 0.5
end_noise: 0.01
training_frequency: 1
running_steps: 250000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/td3/"
model_dir: "./models/td3/"
