agent: "MFQ"  # the learning algorithms_marl
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "MF_Q_network"
representation: "Basic_Identical"
vectorize: "Dummy_Pettingzoo"
runner: "Pettingzoo_Runner"

use_recurrent: False
rnn:
representation_hidden_size: [64, ]
q_hidden_size: [64, ]  # the units for each hidden layer
activation: "relu"

seed: 1
parallels: 16
buffer_size: 200000
batch_size: 256
learning_rate: 0.001
gamma: 0.95  # discount factor
double_q: True  # use double q learning
temperature: 0.1  # softmax for policy

start_greedy: 1.0
end_greedy: 0.05
decay_step_greedy: 2500000
start_training: 1000  # start training after n episodes
running_steps: 10000000  # 10M
train_per_step: False  # True: train model per step; False: train model per episode.
training_frequency: 1
sync_frequency: 100

use_grad_clip: False
grad_clip_norm: 0.5

n_tests: 5
test_period: 100

eval_interval: 100000
test_episode: 5
log_dir: "./logs/mfq/"
model_dir: "./models/mfq/"
