agent: "DDPG"
env_name: "MuJoCo"
env_id: "Ant-v4"
policy: "DDPG_Policy"
representation: "Basic_Identical"

representation_hidden_size:  # If you choose Basic_Identical representation, then ignore this value
actor_hidden_size: [256, ]
critic_hidden_size: [256, ]
activation: "LeakyReLU"

seed: 19089
parallels: 4  # number of environments
n_size: 50000  # replay buffer size
batch_size: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.01

start_noise: 0.5
end_noise: 0.01
training_frequency: 1
running_steps: 250000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/ddpg/"
model_dir: "./models/ddpg/"
