agent: "MFAC"  # the learning algorithms_marl
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "Categorical_MFAC_policy"
representation: "Basic_Identical"
vectorize: "Dummy_MAS"
runner: "MARL"

#train_at_step: True
representation_hidden_size: [32, ]  # the units for each hidden layer
actor_hidden_size: [128, ]
critic_hidden_size: [128, ]

lr_a: 0.001
lr_c: 0.001
training_steps: 30000
training_frequency: 1
nsteps: 256
nepoch: 5
nminibatch: 1
temperature: 0.1  # softmax for policy
tau: 0.005  # soft update factor for MFAC

vf_coef: 0.25
ent_coef: 0.01
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.95  # discount factor
lam: 0.95

n_tests: 5
test_period: 100

use_advnorm: False
use_gae: True

log_dir: "./logs/mfac/"
model_dir: "./models/mfac/"
