agent: "COMA"  # the learning algorithms_marl
env_name: "StarCraft2"
env_id: "corridor"
fps: 15
policy: "Categorical_COMA_Policy"
representation: "Basic_RNN"
vectorize: "Subproc_StarCraft2"
runner: "StarCraft2_Runner"

use_recurrent: True
rnn: "GRU"
recurrent_layer_N: 1
fc_hidden_sizes: [64, ]
recurrent_hidden_size: 64
N_recurrent_layers: 1
dropout: 0
normalize: "LayerNorm"
initialize: "orthogonal"
gain: 0.01

actor_hidden_size: [64, ]
critic_hidden_size: [128, 128]
activation: "relu"

seed: 1
parallels: 8
buffer_size: 8
n_epoch: 1
n_minibatch: 1
learning_rate_actor: 0.0007
learning_rate_critic: 0.0007

clip_grad: 10
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.95  # discount factor
td_lambda: 0.8

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 1000000
sync_frequency: 200

use_global_state: True  # if use global state to replace merged observations
use_advnorm: False
use_gae:
gae_lambda: 0.95

start_training: 1
running_steps: 10000000
train_per_step: True
training_frequency: 1

test_steps: 10000
eval_interval: 100000
test_episode: 16
log_dir: "./logs/coma/"
model_dir: "./models/coma/"
