agent: "NPG"
env_name: "MuJoCo"
env_id: "Ant-v4"
env_seed: 1  # The random seed of the environment.
vectorize: "DummyVecEnv"
policy: "Gaussian_AC"
representation: "Basic_MLP"
learner: "NPG_Learner"
runner: "DRL"

representation_hidden_size: [256, 256]
actor_hidden_size: []
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 16
running_steps: 1000000  # 1M
horizon_size: 256  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epochs: 1
n_minibatch: 1
learning_rate: 0.0007  # 7e-4

gamma: 0.99
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_grad_clip: True  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: True  # Whether to use observation normalization trick.
use_rewnorm: True  # Whether to use reward normalization trick.
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/npg/"
model_dir: "./models/npg/"