agent: "DRQN"
env_name: "Box2D"
env_id: "CarRacing-v2"
vectorize: "Dummy_Gym"
policy: "DRQN_Policy"
representation: "Basic_CNN"
runner: "DRL"
rnn: "LSTM"

# the following three arguments are for "Basic_CNN" representation.
filters: [16, 16, 32]  #  [16, 16, 32, 32]
kernels: [8, 4, 3]  # [8, 6, 4, 4]
strides: [4, 2, 1]  # [2, 2, 2, 2]

recurrent_hidden_size: 512
recurrent_layer_N: 1
dropout: 0
activation: 'relu'

seed: 1
parallels: 2
buffer_size: 200
batch_size: 8  # batch size for training
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 50000
sync_frequency: 500
training_frequency: 1
running_steps: 2000000
start_training: 1000
lookup_length: 50

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 100000
test_episode: 1
log_dir: "./logs/drqn/"
model_dir: "./models/drqn/"
