agent: "PPO_Clip"
env_name: "toy"
env_id: "CartPole-v0"
representation: "Basic_MLP"
policy: "Categorical_AC"

representation_hidden_size: [128,]
actor_hidden_size: [128,]
critic_hidden_size: [128,]

training_steps: 30000
nsteps: 256
nepoch: 8
nminibatch: 8
learning_rate: 0.0004

vf_coef: 0.25
ent_coef: 0.01
clip_range: 0.2
gamma: 0.98
lam: 0.95

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

logdir: "./logs/ppoclip/"
modeldir: "./models/ppoclip/"