agent: "QTRAN_base"  # Options: QTRAN_base, QTRAN_alt
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "Qtran_Mixing_Q_network"
representation: "Basic_MLP"
vectorize: "Dummy_Pettingzoo"
runner: "Pettingzoo_Runner"

use_recurrent: False
rnn:
representation_hidden_size: [256, ]
q_hidden_size: [256, ]  # the units for each hidden layer
activation: "relu"

hidden_dim_mixing_net: 64  # hidden units of mixing network
hidden_dim_hyper_net: 64  # hidden units of hyper network
qtran_net_hidden_dim: 64
lambda_opt: 1.0
lambda_nopt: 1.0

seed: 1
parallels: 16
buffer_size: 100000
batch_size: 256
learning_rate: 0.001
gamma: 0.99  # discount factor
double_q: True  # use double q learning

start_greedy: 1.0
end_greedy: 0.05
decay_step_greedy: 2500000
start_training: 1000  # start training after n episodes
running_steps: 10000000  # 10M
train_per_step: False  # True: train model per step; False: train model per episode.
training_frequency: 1
sync_frequency: 200

use_grad_clip: False
grad_clip_norm: 0.5

eval_interval: 100000
test_episode: 5
log_dir: "./logs/qtran/"
model_dir: "./models/qtran/"
