agent: "PG"
env_name: "Box2D"
env_id: "BipedalWalker-v3"
representation: "Basic_MLP"
vectorize: "Dummy_Gym"
policy: "Gaussian_Actor"
runner: "DRL"

representation_hidden_size: [128,]
actor_hidden_size: [128,]
activation: 'relu'
activation_action: 'tanh'

seed: 1
parallels: 10
running_steps: 100000
horizon_size: 1024  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epoch: 3
n_minibatch: 1
learning_rate: 0.0004

ent_coef: 0.01
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.98
use_gae: False
gae_lambda: 0.95
use_advnorm: False

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 10000
test_episode: 1
log_dir: "./logs/pg/"
model_dir: "./models/pg/"