agent: "SACDIS"
env_name: "Classic Control"
env_id: "Acrobot-v1"
policy: "Discrete_SAC"
representation: "Basic_MLP"

representation_hidden_size: [256,]
actor_hidden_size: [128,128,]
critic_hidden_size: [128,128,]
activation: "ReLU"

nsize: 20000
parallels: 16
batchsize: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.01
gamma: 0.98
tau: 0.005

start_noise: 0.25
end_noise: 0.05
training_frequency: 2
training_steps: 50000
start_training: 2000
action_type: "DISCRETE"

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 1
logdir: "./logs/sac/"
modeldir: "./models/sac/"